### ISSUE TITLE
"Central has encountered a system permissions issue"

### ISSUE THREAD

**Issue by cshao06** [PietJankbal/powershell-wrapper-for-wine#4] opened 2020-12-04 04:44 UTC
I was following the discussions in other issues of this repo. I fixed a couple of issues that have already been mentioned, including robocopy, powershell, disable-gpu and arial font. The installer failed, "as expected", and then I ran "wine Waves\ Central.exe" directly from the Waves Central folder. However, I'm still getting the following error in the Waves Central gui.

fixing permission and ownership

Central has encountered a system permissions issue.

Any idea? I'd really appreciate it.

**Comment by PietJankbal** [comment] 2020-12-04 18:18
Hi,

Could you paste the complete console output? Also, what version of wine and Waves did you use?

Thanks

**Comment by cshao06** [comment] 2020-12-05 03:52
I tried a fresh wineprefix today and still had no luck.

I'm using multilib/wine-staging 5.22-1 from Arch Linux's repo. I tried both Central 11 and 12 but they had the same issue. It failed at Central's "permissionFixer".

I also saw  `Register-WMIEvent: The term 'Register-WMIEvent' is not recognized as the name of ... Check the spelling of the name, or if a path was included, verify that the path ...` on the pwsh shell. However, I saw you mentioned that this is not a fatal error in this [thread](https://forum.winehq.org/viewtopic.php?f=8&t=33247) on the wine forum.

I think the powershell is running okay except that I got a "Program Error" window whenever I close the shell manually.

The relevant error messages in linux command line are as follows.

```
22:26:55 [error]    ElectronMainLiveProcess::start process has reported an issue ---
{"batch_file":"C:\\users\\username\\Application Data\\Waves Audio\\Waves Central\\Logs\\permissionFixer\\permission-fixer_12-20201204222650.py
","batch_line":185,"current_working_dir":"C:\\Program Files\\Waves Central","doing":"change mode of 'C:\\Program Files (x86)\\VSTPlugIns' t
o '{'names': ['username'], 'codes': ['S-1-5-32-549', 'S-1-1-0']}, 1180095, +'","exception_str":"(1336, 'AddAccesAllowedAce', 'Invalid ACL.')",
"exception_type":"error","instl_class":"Chmod(path=r\"C:\\Program Files (x86)\\VSTPlugIns\", mode=\"a+rwX\", ignore_if_not_exist=True, prog
_num=31)","instl_version":"instl version 2.1.10.4 2020-11-10 16:32:55.164972 BS-WIN48","local_time":"2020-12-04_22.26.54","ls of problem fi
le":{"flags":"[]","full path":"C:/Program Files (x86)/VSTPlugIns","group":"HOMEDESKTOP\\None","modification time":"2020/12/05 02:49:55","us
er":"HOMEDESKTOP\\username"},"major_stage":"doit","obj__dict__":{"capture_stdout":false,"child_batch_commands":[],"command_time_sec":0.0013834
9999999976,"detach":false,"essential_action_counter":0,"ignore_all_errors":false,"ignore_if_not_exist":true,"ignore_specific_exit_codes":[]
,"in_sub_accum":false,"mode":"a+rwX","out_file":null,"own_progress_count":1,"path":"C:\\Program Files (x86)\\VSTPlugIns","prog_num":31,"rec
ursive":false,"reply_config_var":null,"reply_environ_var":null,"report_own_progress":true,"runtime_progress_num":31,"script":false,"shell":
false,"skip_action":false,"stderr":"","stderr_means_err":true,"suspend":0},"operating_system":"Windows 6.1.7601","progress_counter":31,"pyt
hon_version":"3.6.6.final.0","stage":"doit.Prefix C:\\Program Files (x86)\\VSTPlugIns..."}
...

---
{"batch_file":"pyinstl\\instl_main.py","batch_line":175,"current_working_dir":"C:\\Program Files\\Waves Central","doing":"change mode of 'C
:\\Program Files (x86)\\VSTPlugIns' to '{'names': ['username'], 'codes': ['S-1-5-32-549', 'S-1-1-0']}, 1180095, +'","exception_str":"(1336, 'A
ddAccesAllowedAce', 'Invalid ACL.')","exception_type":"error","instl_class":"Chmod(path=r\"C:\\Program Files (x86)\\VSTPlugIns\", mode=\"a+
rwX\", ignore_if_not_exist=True, prog_num=31)","instl_version":"instl version 2.1.10.4 2020-11-10 16:32:55.164972 BS-WIN48","local_time":"2
020-12-04_22.26.55","ls of problem file":{"flags":"[]","full path":"C:/Program Files (x86)/VSTPlugIns","group":"HOMEDESKTOP\\None","modific
ation time":"2020/12/05 02:49:55","user":"HOMEDESKTOP\\username"},"major_stage":"doit","obj__dict__":{"capture_stdout":false,"child_batch_comm
ands":[],"command_time_sec":0.00138349999999976,"detach":false,"essential_action_counter":0,"ignore_all_errors":false,"ignore_if_not_exist"
:true,"ignore_specific_exit_codes":[],"in_sub_accum":false,"mode":"a+rwX","out_file":null,"own_progress_count":1,"path":"C:\\Program Files
(x86)\\VSTPlugIns","prog_num":31,"recursive":false,"reply_config_var":null,"reply_environ_var":null,"report_own_progress":true,"runtime_pro
gress_num":31,"script":false,"shell":false,"skip_action":false,"stderr":"","stderr_means_err":true,"suspend":0},"operating_system":"Windows
 6.1.7601","progress_counter":31,"python_version":"3.6.6.final.0","stage":"doit.Prefix C:\\Program Files (x86)\\VSTPlugIns..."}
...

Traceback (most recent call last):
  File "instl", line 15, in <module>
  File "pyinstl\instl_main.py", line 175, in instl_own_main
  File "pyinstl\instlDoIt.py", line 37, in do_command
  File "pyinstl\instlInstanceBase.py", line 445, in run_batch_file
  File "C:\users\username\Application Data\Waves Audio\Waves Central\Logs\permissionFixer\permission-fixer_12-20201204222650.py", line 185, in
 <module>
    chmod_014_31()
  File "pybatch\fileSystemBatchCommands.py", line 646, in __call__
pywintypes.error: (1336, 'AddAccesAllowedAce', 'Invalid ACL.')
[1652] Failed to execute script instl


22:26:55 [error]    ElectronMainLiveProcess::start process has reported an issue ---
{"batch_file":"pyinstl\\instl_main.py","batch_line":181,"current_working_dir":"C:\\Program Files\\Waves Central","doing":"calling subproces
s 'C:\\Program Files\\Waves Central\\resources\\res\\external\\bin\\instl.bundle\\Contents\\Win64\\instl.exe doit --in C:\\users\\username\\Ap
plication Data\\Waves Audio\\Waves Central\\Logs\\permissionFixer\\permission-fixer_12-20201204222650.yaml --out C:\\users\\username\\Applicat
ion Data\\Waves Audio\\Waves Central\\Logs\\permissionFixer\\permission-fixer_12-20201204222650.py --log C:\\users\\username\\Application Data
\\Waves Audio\\Waves Central\\Logs\\permissionFixer\\doit-output-12-20201204222650.log --run'","exception_str":"Command '['C:\\\\Program Fi
les\\\\Waves Central\\\\resources\\\\res\\\\external\\\\bin\\\\instl.bundle\\\\Contents\\\\Win64\\\\instl.exe', 'doit', '--in', 'C:\\\\user
s\\\\username\\\\Application Data\\\\Waves Audio\\\\Waves Central\\\\Logs\\\\permissionFixer\\\\permission-fixer_12-20201204222650.yaml', '--o
ut', 'C:\\\\users\\\\username\\\\Application Data\\\\Waves Audio\\\\Waves Central\\\\Logs\\\\permissionFixer\\\\permission-fixer_12-2020120422
2650.py', '--log', 'C:\\\\users\\\\username\\\\Application Data\\\\Waves Audio\\\\Waves Central\\\\Logs\\\\permissionFixer\\\\doit-output-12-2
0201204222650.log', '--run']' returned non-zero exit status 4294967295.","exception_type":"CalledProcessError","instl_class":"Subprocess(r\
"C:\\Program Files\\Waves Central\\resources\\res\\external\\bin\\instl.bundle\\Contents\\Win64\\instl.exe\", r\"doit\", r\"--in\", r\"C:\\
users\\username\\Application Data\\Waves Audio\\Waves Central\\Logs\\permissionFixer\\permission-fixer_12-20201204222650.yaml\", r\"--out\", r
\"C:\\users\\username\\Application Data\\Waves Audio\\Waves Central\\Logs\\permissionFixer\\permission-fixer_12-20201204222650.py\", r\"--log\
", r\"C:\\users\\username\\Application Data\\Waves Audio\\Waves Central\\Logs\\permissionFixer\\doit-output-12-20201204222650.log\", r\"--run\
", own_progress_count=0)","instl_version":"instl version 2.1.10.4 2020-11-10 16:32:55.164972 BS-WIN48","local_time":"2020-12-04_22.26.55","
major_stage":"Subprocess","obj__dict__":{"capture_stdout":false,"child_batch_commands":[],"command_time_sec":3.7115095,"detach":false,"esse
ntial_action_counter":0,"ignore_all_errors":false,"ignore_specific_exit_codes":[],"in_sub_accum":false,"message":null,"out_file":null,"own_
progress_count":0,"prog_num":0,"recursive":false,"reply_config_var":null,"reply_environ_var":null,"report_own_progress":true,"runtime_progr
ess_num":0,"script":false,"shell":false,"skip_action":false,"stderr":"---\r\n{\"batch_file\":\"C:\\\\users\\\\username\\\\Application Data\\\\
Waves Audio\\\\Waves Central\\\\Logs\\\\permissionFixer\\\\permission-fixer_12-20201204222650.py\",\"batch_line\":185,\"current_working_dir
\":\"C:\\\\Program Files\\\\Waves Central\",\"doing\":\"change mode of 'C:\\\\Program Files (x86)\\\\VSTPlugIns' to '{'names': ['username'], '
codes': ['S-1-5-32-549', 'S-1-1-0']}, 1180095, +'\",\"exception_str\":\"(1336, 'AddAccesAllowedAce', 'Invalid ACL.')\",\"exception_type\":\
"error\",\"instl_class\":\"Chmod(path=r\\\"C:\\\\Program Files (x86)\\\\VSTPlugIns\\\", mode=\\\"a+rwX\\\", ignore_if_not_exist=True, prog_
num=31)\",\"instl_version\":\"instl version 2.1.10.4 2020-11-10 16:32:55.164972 BS-WIN48\",\"local_time\":\"2020-12-04_22.26.54\",\"ls of p
roblem file\":{\"flags\":\"[]\",\"full path\":\"C:/Program Files (x86)/VSTPlugIns\",\"group\":\"HOMEDESKTOP\\\\None\",\"modification time\"
:\"2020/12/05 02:49:55\",\"user\":\"HOMEDESKTOP\\\\username\"},\"major_stage\":\"doit\",\"obj__dict__\":{\"capture_stdout\":false,\"child_batc
h_commands\":[],\"command_time_sec\":0.00138349999999976,\"detach\":false,\"essential_action_counter\":0,\"ignore_all_errors\":false,\"igno
re_if_not_exist\":true,\"ignore_specific_exit_codes\":[],\"in_sub_accum\":false,\"mode\":\"a+rwX\",\"out_file\":null,\"own_progress_count\"
:1,\"path\":\"C:\\\\Program Files (x86)\\\\VSTPlugIns\",\"prog_num\":31,\"recursive\":false,\"reply_config_var\":null,\"reply_environ_var\"
:null,\"report_own_progress\":true,\"runtime_progress_num\":31,\"script\":false,\"shell\":false,\"skip_action\":false,\"stderr\":\"\",\"std
err_means_err\":true,\"suspend\":0},\"operating_system\":\"Windows 6.1.7601\",\"progress_counter\":31,\"python_version\":\"3.6.6.final.0\",
\"stage\":\"doit.Prefix C:\\\\Program Files (x86)\\\\VSTPlugIns...\"}\r\n...\r\n\r\n---\r\n{\"batch_file\":\"pyinstl\\\\instl_main.py\",\"b
atch_line\":175,\"current_working_dir\":\"C:\\\\Program Files\\\\Waves Central\",\"doing\":\"change mode of 'C:\\\\Program Files (x86)\\\\V
STPlugIns' to '{'names': ['username'], 'codes': ['S-1-5-32-549', 'S-1-1-0']}, 1180095, +'\",\"exception_str\":\"(1336, 'AddAccesAllowedAce', '
Invalid ACL.')\",\"exception_type\":\"error\",\"instl_class\":\"Chmod(path=r\\\"C:\\\\Program Files (x86)\\\\VSTPlugIns\\\", mode=\\\"a+rwX
\\\", ignore_if_not_exist=True, prog_num=31)\",\"instl_version\":\"instl version 2.1.10.4 2020-11-10 16:32:55.164972 BS-WIN48\",\"local_tim
e\":\"2020-12-04_22.26.55\",\"ls of problem file\":{\"flags\":\"[]\",\"full path\":\"C:/Program Files (x86)/VSTPlugIns\",\"group\":\"HOMEDE
SKTOP\\\\None\",\"modification time\":\"2020/12/05 02:49:55\",\"user\":\"HOMEDESKTOP\\\\username\"},\"major_stage\":\"doit\",\"obj__dict__\":{
\"capture_stdout\":false,\"child_batch_commands\":[],\"command_time_sec\":0.00138349999999976,\"detach\":false,\"essential_action_counter\"
:0,\"ignore_all_errors\":false,\"ignore_if_not_exist\":true,\"ignore_specific_exit_codes\":[],\"in_sub_accum\":false,\"mode\":\"a+rwX\",\"o
ut_file\":null,\"own_progress_count\":1,\"path\":\"C:\\\\Program Files (x86)\\\\VSTPlugIns\",\"prog_num\":31,\"recursive\":false,\"reply_co
nfig_var\":null,\"reply_environ_var\":null,\"report_own_progress\":true,\"runtime_progress_num\":31,\"script\":false,\"shell\":false,\"skip
_action\":false,\"stderr\":\"\",\"stderr_means_err\":true,\"suspend\":0},\"operating_system\":\"Windows 6.1.7601\",\"progress_counter\":31,
\"python_version\":\"3.6.6.final.0\",\"stage\":\"doit.Prefix C:\\\\Program Files (x86)\\\\VSTPlugIns...\"}\r\n...\r\n\r\nTraceback (most re
cent call last):\r\n  File \"instl\", line 15, in <module>\r\n  File \"pyinstl\\instl_main.py\", line 175, in instl_own_main\r\n  File \"py
instl\\instlDoIt.py\", line 37, in do_command\r\n  File \"pyinstl\\instlInstanceBase.py\", line 445, in run_batch_file\r\n  File \"C:\\user
s\\username\\Application Data\\Waves Audio\\Waves Central\\Logs\\permissionFixer\\permission-fixer_12-20201204222650.py\", line 185, in <modul
e>\r\n    chmod_014_31()\r\n  File \"pybatch\\fileSystemBatchCommands.py\", line 646, in __call__\r\npywintypes.error: (1336, 'AddAccesAllo
wedAce', 'Invalid ACL.')\r\n[1652] Failed to execute script instl\r\n","stderr_means_err":true,"subprocess_args":["doit","--in","C:\\users\
\username\\Application Data\\Waves Audio\\Waves Central\\Logs\\permissionFixer\\permission-fixer_12-20201204222650.yaml","--out","C:\\users\\c
shao\\Application Data\\Waves Audio\\Waves Central\\Logs\\permissionFixer\\permission-fixer_12-20201204222650.py","--log","C:\\users\\username
\\Application Data\\Waves Audio\\Waves Central\\Logs\\permissionFixer\\doit-output-12-20201204222650.log","--run"],"subprocess_exe":"C:\\Pr
ogram Files\\Waves Central\\resources\\res\\external\\bin\\instl.bundle\\Contents\\Win64\\instl.exe","suspend":0},"operating_system":"Windo
ws 6.1.7601","progress_counter":0,"python_version":"3.6.6.final.0","stage":""}
...


22:26:55 [error]    ElectronMainLiveProcess::start process has reported an issue Traceback (most recent call last):
  File "instl", line 15, in <module>
  File "pyinstl\instl_main.py", line 181, in instl_own_main
  File "pyinstl\instlMisc.py", line 38, in do_command
  File "pyinstl\instlMisc.py", line 269, in do_run_process
  File "pybatch\subprocessBatchCommands.py", line 116, in __call__

22:26:55 [error]    ElectronMainLiveProcess::start process has reported an issue   File "subprocess.py", line 369, in check_retur
ncode
subprocess.CalledProcessError: Command '['C:\\Program Files\\Waves Central\\resources\\res\\external\\bin\\instl.bundle\\Contents\\Win64\\i
nstl.exe', 'doit', '--in', 'C:\\users\\username\\Application Data\\Waves Audio\\Waves Central\\Logs\\permissionFixer\\permission-fixer_12-2020
1204222650.yaml', '--out', 'C:\\users\\username\\Application Data\\Waves Audio\\Waves Central\\Logs\\permissionFixer\\permission-fixer_12-2020
1204222650.py', '--log', 'C:\\users\\username\\Application Data\\Waves Audio\\Waves Central\\Logs\\permissionFixer\\doit-output-12-20201204222
650.log', '--run']' returned non-zero exit status 4294967295.
[1708] Failed to exe
22:26:55 [error]    ElectronMainLiveProcess::start process has reported an issue cute script instl

```

**Comment by cshao06** [comment] 2020-12-05 05:06
I fixed the problem by manually changing the ACL of the problematic folders using Get-Acl command in the powershell. However, the Waves license I got is v12 and v12 plugins only work on windows 10. Central won't run in windows 10.

Do you know any workaround? Thanks!

**Comment by cshao06** [comment] 2020-12-05 07:55
It's working!! I just installed the v12 plugins with win7 and then use winecfg to switch to win10. I can then wrap the plugins with linvst or linvst3 and most of them work in REAPER. CLA-76 could load the plugin but only outputs a big pop sound somehow.

This is absolutely amazing! Thanks for making this happen.

**Comment by PietJankbal** [comment] 2020-12-06 22:06
Hi, could you explain what you exactly did with "I fixed the problem by manually changing the ACL of the problematic folders using Get-Acl command in the powershell. "? Might be useful for others who run into same problem

Regards

**Comment by cshao06** [comment] 2020-12-07 00:14
I first looked at the logs in `drive_c/users/cshao/Application\ Data/Waves\ Audio/Waves\ Central/Logs/permissionFixer/` as Central failed at the permissionFixer. I saw the exact folder that it failed at. Then I launched the powershell in the wine prefix and use `Get-Acl` and `Set-Acl`, described [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-acl?view=powershell-7.1), to fix the acl of the faulty folder.
Then run the Central app again, see what folder failed and fix it. Keep going until they are all fixed.

**Comment by PietJankbal** [comment] 2020-12-22 08:30
Hi, I can confirm the permission issue; After an install of installer I have here lying Waves updates itsself to version 12.0.11 and then it stops at "fixing permission issue". It looks like an issue only present with newest Waves versions

I tried other hack to get around this issue: copy a stub wine fake .exe into Waves` "instl.exe" to replace it:

`cp -rf ~/.wine/drive_c/windows/system32/where.exe ~/.wine/drive_c/Program\ Files/Waves\ Central/resources/res/external/bin/instl.bundle/Contents/Win64/instl.exe`

That allowed me again to get into login window but I don`t know if this hack has any (unwanted) side-effects....

**Comment by PietJankbal** [comment] 2021-01-29 17:35
Hi  cshao06 , 

Would you mind to paste the exact command you used (with Set-ACL and Get-ACL)? 
I cannot get around the "permission issue" , it seems to first choke in Program Files x86\VSTPlugins; what exact command should i then use?

Thanks in advance

**Comment by PietJankbal** [comment] 2021-02-05 11:44
[RtlAddAccessAllowedAceEx.txt](https://github.com/PietJankbal/powershell-wrapper-for-wine/files/5932178/RtlAddAccessAllowedAceEx.txt)


The attached hack allowed me to get around the "system permissions issue" at least into the login screen. Is it possible you/anyone could test if it fixes the issue for Waves?

**Comment by th8a** [comment] 2021-02-07 09:55
@PietJankbal 

I figured out what he did to get it working, and can confirm that it works to get the installer going. You just run powershell in the target wine prefix and enter the following commands.  Replace 'th8a' with your user name.



Get-Acl -Path "C:\users\th8a\Application Data\Waves Audio\Caches" | Set-Acl -Path "C:\Program Files (
x86)\VSTPlugIns"

Get-Acl -Path "C:\users\th8a\Application Data\Waves Audio\Caches" | Set-Acl -Path "C:\Program Files (
x86)\Common Files\VST3"

Get-Acl -Path "C:\users\th8a\Application Data\Waves Audio\Caches" | Set-Acl -Path "C:\Program Files\
Common Files\Avid\Audio\Plug-Ins"

Get-Acl -Path "C:\users\th8a\Application Data\Waves Audio\Caches" | Set-Acl -Path "C:\Program Files (
x86)\Common Files\WPAPI"


That gets you to the login screen... however, I am still getting an error somewhere in the middle of the install process that I am still trying to figure out... Good luck! Waves has always been a tricky one to install in wine, and it seems like it just gets harder with each update instead of easier. lol

**Comment by PietJankbal** [comment] 2021-02-08 23:15
@th8a:

Thanks for the info of the workround! Meanwhile I`ve been trying to fix this upstream in wine ittself. There might be a possibility this gets fixed soon I hope. I`ll update the info here then; If you encounter  more errors feel free to post here. Regards

**Comment by PietJankbal** [comment] 2021-03-05 08:17
This "Central has encountered a system permissions issue"  error should be fixed by a yesterday`s  commit to  Wine-Staging, so in upcoming Wine-Staging-6.4 (next week) this issue should be gone.

**Comment by PietJankbal** [comment] 2021-04-01 21:40
Closing this one, for subsequent issues please open new bugreports

**Closed as completed by PietJankbal** 2021-04-01 21:40 UTC

**Comment by georgefetcher** [comment] 2023-06-09 04:01
How to fix the "waves central has encountered a system permissions issue" error when starting up on macos? There is a way! This also solves the problem with the licenses, if there is one.

In order to fully fix Waves Central and restore its startup and eliminate the problems with license activation - you need to delete all files and folders where the keyword "waves" (search in finder) in these places:

1)
/Library/Application Support/   
(Delete here folders "Waves" / "Waves Audio" / "Waves Central", some of them may be folders, if you see them, delete them)

2)
/user/Library/Application Support/    
(Delete here folders "Waves" / "Waves Audio" / "Waves Central", folders may be some of them if you see them, delete)

3)
/Library/PrivilegedHelperTools/
(Delete all files/file with the word "waves")

4)
/user/Library/Preferences/
(Delete all files with the word "waves")

5)
/Applications/
(delete completely the Waves folder)

6)
After all manipulations - RESTART the computer, and then download the clean Waves Central in the applications and run. Now everything should go smoothly!

P.S..
If a folder is not deleting, and you get an error that the files/folder is locked by the system, you need to run a terminal and enter the command:
"chflags -R nouchg". 
After that, hit "space" and DRAG the folder (that won't get deleted) directly to the terminal window (its address will appear). Here's how it should look like in terminal window for example:
"chflags -R nouchg /Applications/Waves".
Next - press enter, enter user password (it won't show) and press "enter" again. Now any folder will be deleted without any problems.


I have suffered a lot of time before I managed to fix my problem after the system recovery, none of the methods on dozens of websites did not help, so I decided to write a really working method for other users, because before that I have not found an answer to my question :)
Good luck!
